---
swagger: "2.0"
info:
  description: "Swagger tutorial"
  version: "1.0.0"
  title: "Swagger tutorial"
host: "virtserver.swaggerhub.com"
basePath: "/jelles0995/DevOps_Ass2/1.0.0"
schemes:
- "https"
- "http"
paths:
  /student:
    post:
      summary: "Add a new student"
      description: ""
      operationId: "add_student"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Student"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "integer"
            format: "int64"
        "405":
          description: "Invalid input"
        "409":
          description: "already exists"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /student/{student_id}:
    get:
      summary: "Find student by ID"
      description: "Returns a single student"
      operationId: "get_student_by_id"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "ID of student to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "student not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      description: "Delete a student by ID"
      operationId: "delete_student"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "ID of student to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "student not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Student:
    type: "object"
    properties:
      id:
        type: "integer"
      first_name:
        type: "string"
      last_name:
        type: "string"
      grades:
        type: "array"
        items:
          $ref: "#/definitions/Student_grades"
    example:
      last_name: "last_name"
      id: 0
      grades:
      - subject: "subject"
        grade: 6
        entered: "2000-01-23T04:56:07.000+00:00"
      - subject: "subject"
        grade: 6
        entered: "2000-01-23T04:56:07.000+00:00"
      first_name: "first_name"
  Student_grades:
    type: "object"
    properties:
      subject:
        type: "string"
      entered:
        type: "string"
        format: "date-time"
      grade:
        type: "integer"
        minimum: 0
        maximum: 10
    example:
      subject: "subject"
      grade: 6
      entered: "2000-01-23T04:56:07.000+00:00"
